### ISSUE TITLE
info

### ISSUE THREAD

**Issue by BunnyNomics101** [bezrazli4n0/p2swap-protocol#1]
Hi,
Thanks for sharing this. Did you make it yourself or forked it somewhere else?
Why not make the order address independent of person 2 and list it in a pool free for all?

**Comment by bezrazli4n0** [comment]
> Hi,
> Thanks for sharing this. Did you make it yourself or forked it somewhere else?
> Why not make the order address independent of person 2 and list it in a pool free for all?

Hello, I make this by myself for riptide hackathon. Order depends on person2 address because of my initial idea. If you have more questions feel free to

**Comment by BunnyNomics101** [comment]
I can't add you due to your privacy settings

**Comment by bezrazli4n0** [comment]
> I can't add you due to your privacy settings

Okay, lets try discord: b3zrazli4n0#5690
